[package]
name = "mdblog"
version = "0.18.1"
authors = ["FuGangqiang <fu_gangqiang@qq.com>"]
description = "static site generator from markdown files."
repository = "https://github.com/FuGangqiang/mdblog.rs"
homepage = "https://github.com/FuGangqiang/mdblog.rs"
documentation = "https://docs.rs/mdblog"
keywords = ["blog", "markdown", "static", "site", "generator"]
categories = ["command-line-utilities"]
license = "MIT"
readme = "README.md"
edition = "2021"

[[bin]]
name = "mdblog"
doc = false

[dependencies]
log = "0.4"
env_logger = "0.9"
clap = "3.0.0-beta.4"
config = "0.11.0"
derive_more = { version = "0.99", features = ["display", "from"]}
pulldown-cmark = { version = "0.8", default-features = false, features = ["simd"] }
serde = { version = "1.0", features = ["rc", "std", "derive"]}
serde_json = "1.0"
serde_yaml = "0.8"
toml = "0.5"
tera = "1.12"
walkdir = "2.3"
tempfile = "3"
rocket = "0.4"
rocket_contrib = "0.4"
open = "2.0"
notify = "4.0"
glob = "0.3"
shellexpand = "2.1"
chrono = { version = "0.4", features = ["serde"] }
